### ISSUE TITLE
Не могу играть по сети

### ISSUE THREAD

**Issue by devmansurov** [ContraMod/Launcher#1]
Привет я читал инструкцию для онлайн игры и не смог понят на что именно заменить мой IP в этом шаге

**Переключите IP сети на 26.X.X.X внутри опций игры.**

Просто не отображается игроки у меня сейчас внутри игры.

**Comment by devmansurov** [comment]
Был бы хорошо если еще в будущем будут видео инструкции по сетеаой игры

**Comment by ThePredatorBG** [comment]
@devmansurov https://www.youtube.com/watch?v=wQoktTvNQGs&ab_channel=JesaiX
